import requests
import json
from datetime import datetime
import time
from config import headers,headers_liqiming
from conn_mysql import get_db_cursor


def update_order_wuliao():
    """编制物料'id': 31850第一次新增时id是没有的"""
    json_data = {
    'logsType': 'B131',
    'orderrequestMaterialVoList': [
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '6',
            'materialCode': 'BLSMILEY25003',
            'materialName': '加厚耐磨地贴',
            'materialDescribe': '',
            'materialWidth': 4000,
            'materialHeight': 4000,
            'materialDepth': '0',
            'approvedQuantity': 2,
            'quantity': 2,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 2,
            'amount': '2.0000',
            'taxType': '6',
            'amountTax': 0.11,
            'nodes': '加厚耐磨地贴',
            'requestShippingDate': '',
            'id': 31850,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '6',
            'materialCode': 'AAAA123456720',
            'materialName': '晨光(M&G)文具A4/5mm彩色三角杆抽杆夹 办公报告夹拉杆夹学生考试收纳',
            'materialDescribe': '',
            'materialWidth': 1000,
            'materialHeight': 500,
            'materialDepth': 1000,
            'approvedQuantity': 2,
            'quantity': 2,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 22.44,
            'amount': '44.8800',
            'taxType': '6',
            'amountTax': 2.54,
            'nodes': '晨光(M&G)文具A4/5mm彩色三角杆抽杆夹 办公报告夹拉杆夹学生考试收纳',
            'requestShippingDate': '',
            'id': 31851,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '6',
            'materialCode': 'AAAA123456721',
            'materialName': '签字笔',
            'materialDescribe': '',
            'materialWidth': 900,
            'materialHeight': 700,
            'materialDepth': 700,
            'approvedQuantity': 3,
            'quantity': 3,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 123.78,
            'amount': '371.3400',
            'taxType': '6',
            'amountTax': 21.02,
            'nodes': '签字笔',
            'requestShippingDate': '',
            'id': 31852,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '3',
            'materialCode': 'BK20250130001',
            'materialName': '笔记本',
            'materialDescribe': '',
            'materialWidth': 5,
            'materialHeight': 30,
            'materialDepth': 10,
            'approvedQuantity': 4,
            'quantity': 4,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 6500,
            'amount': '26000.0000',
            'taxType': '3',
            'amountTax': 757.28,
            'nodes': '打印机',
            'requestShippingDate': '',
            'id': 31853,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '6',
            'materialCode': 'AAAA123456730',
            'materialName': '插座usb插排',
            'materialDescribe': '',
            'materialWidth': 100,
            'materialHeight': 10,
            'materialDepth': 20,
            'approvedQuantity': 5,
            'quantity': 5,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 15,
            'amount': '75.0000',
            'taxType': '6',
            'amountTax': 4.25,
            'nodes': '插座usb插排',
            'requestShippingDate': '',
            'id': 31854,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '1',
            'materialCode': 'STDCWL2500001',
            'materialName': '百丽童鞋圆形中岛',
            'materialDescribe': '',
            'materialWidth': 700,
            'materialHeight': 1015,
            'materialDepth': 700,
            'approvedQuantity': 6,
            'quantity': 6,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 112.74,
            'amount': '676.4400',
            'taxType': '1',
            'amountTax': 6.7,
            'nodes': '百丽童鞋圆形中岛',
            'requestShippingDate': '',
            'id': 31855,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '3',
            'materialCode': 'BLTSXDJ250005',
            'materialName': '层板贴',
            'materialDescribe': '',
            'materialWidth': 205,
            'materialHeight': 60,
            'materialDepth': '0',
            'approvedQuantity': 7,
            'quantity': 7,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 100,
            'amount': '700.0000',
            'taxType': '3',
            'amountTax': 20.39,
            'nodes': '层板贴',
            'requestShippingDate': '',
            'id': 31856,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '6',
            'materialCode': 'BLSMILEY25005',
            'materialName': '仿沙滩泡沫雕',
            'materialDescribe': '',
            'materialWidth': 3330,
            'materialHeight': 175,
            'materialDepth': 450,
            'approvedQuantity': 8,
            'quantity': 8,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 13.33,
            'amount': '106.6400',
            'taxType': '6',
            'amountTax': 6.04,
            'nodes': '仿沙滩泡沫雕',
            'requestShippingDate': '',
            'id': 31857,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '9',
            'materialCode': 'ITACLCG257101',
            'materialName': '联想ThinkPad 16+笔记本电脑',
            'materialDescribe': '',
            'materialWidth': '0',
            'materialHeight': '0',
            'materialDepth': '0',
            'approvedQuantity': 9,
            'quantity': 9,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 321.9,
            'amount': '2897.1000',
            'taxType': '9',
            'amountTax': 239.21,
            'nodes': '联想ThinkPad 16+笔记本电脑',
            'requestShippingDate': '',
            'id': 31858,
        },
        {
            'orderId': 11504,
            'orderNo': 'BS202511200025',
            'materialType': '1',
            'taxRate': '6',
            'materialCode': 'BLSMILEY25001',
            'materialName': '黄色渐变饰面板',
            'materialDescribe': '',
            'materialWidth': 2350,
            'materialHeight': 2950,
            'materialDepth': 6,
            'approvedQuantity': 10,
            'quantity': 10,
            'supplierName': '东莞市百丽鞋业有限公司',
            'supplierNo': 'GC000037',
            'price': 21,
            'amount': '210.0000',
            'taxType': '6',
            'amountTax': 11.89,
            'nodes': '黄色渐变饰面板',
            'requestShippingDate': '',
            'id': 31859,
        },
    ],
    'orderrequestMainVo': {
        'id': 11504,
        'orderNo': 'BS202511200025',
        'logRemark': '编制物料信息',
    },
    'docType': '1',
}
    response = requests.post(
    'https://open-gateway-out-test.belle.cn/scs-cpp-web/orderrequestMain/update', headers=headers, json=json_data,)
    print(response.text)


update_order_wuliao() # 编制物料
